language: rust
rust:
  - stable
  - beta
  - nightly
before_script:
  - rustup component add clippy
script:
  # Run build, lint, test
  - make check
  # Run the installation script just to check that it is working
  - make DESTDIR=testdir PREFIX=/usr install
